package py.edu.facitec.mymail.Utils;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

import py.edu.facitec.mymail.Models.Email;

public class Util {
    public static String colors[]={
            "f44336","e91e63","673ab7","3f51b5",
            "03a9f4","009688","4caf50"};

    public static String getRandomColor(){
        return colors[new Random().nextInt(colors.length)+0];
    }

    public static List<Email> getDummyData(){
        return new ArrayList<Email>(){{
            add(new Email("Planilla de precios actuales","Pellentesque eu nunc nec magna viverra mollis. Nulla pulvinar magna sed est mattis, consequat pulvinar leo congue. Sed ante erat, fermentum at auctor ac, molestie in erat. Nunc at mauris nec massa accumsan bibendum. Nunc mollis ipsum a massa lobortis, sed semper risus interdum. Praesent tristique congue mauris a mollis. Ut id felis sodales nibh mollis fringilla quis sed urna. Mauris nec elementum nisl, non imperdiet mi. Donec congue tincidunt turpis, sit amet laoreet tellus suscipit vitae. Cras gravida augue ante, sed dignissim ligula faucibus vitae. Curabitur ut condimentum mi. Cras dignissim, tortor nec iaculis feugiat, lectus massa euismod enim, sed tempus mi arcu in est. Nullam semper dui eros, vel luctus nisl rutrum in.","dummye@gmail.com"));
            add(new Email("Reporte de ventas del primer trimestre","Pellentesque eu nunc nec magna viverra mollis. Nulla pulvinar magna sed est mattis, consequat pulvinar leo congue. Sed ante erat, fermentum at auctor ac, molestie in erat. Nunc at mauris nec massa accumsan bibendum. Nunc mollis ipsum a massa lobortis, sed semper risus interdum. Praesent tristique congue mauris a mollis. Ut id felis sodales nibh mollis fringilla quis sed urna. Mauris nec elementum nisl, non imperdiet mi. Donec congue tincidunt turpis, sit amet laoreet tellus suscipit vitae. Cras gravida augue ante, sed dignissim ligula faucibus vitae. Curabitur ut condimentum mi. Cras dignissim, tortor nec iaculis feugiat, lectus massa euismod enim, sed tempus mi arcu in est. Nullam semper dui eros, vel luctus nisl rutrum in.","batman@gmail.com"));
            add(new Email("Nomina de contactos actualizada","Pellentesque eu nunc nec magna viverra mollis. Nulla pulvinar magna sed est mattis, consequat pulvinar leo congue. Sed ante erat, fermentum at auctor ac, molestie in erat. Nunc at mauris nec massa accumsan bibendum. Nunc mollis ipsum a massa lobortis, sed semper risus interdum. Praesent tristique congue mauris a mollis. Ut id felis sodales nibh mollis fringilla quis sed urna. Mauris nec elementum nisl, non imperdiet mi. Donec congue tincidunt turpis, sit amet laoreet tellus suscipit vitae. Cras gravida augue ante, sed dignissim ligula faucibus vitae. Curabitur ut condimentum mi. Cras dignissim, tortor nec iaculis feugiat, lectus massa euismod enim, sed tempus mi arcu in est. Nullam semper dui eros, vel luctus nisl rutrum in.","abcdario@gmail.com"));
            add(new Email("Lorem ipsum dolor sit amet","Pellentesque eu nunc nec magna viverra mollis. Nulla pulvinar magna sed est mattis, consequat pulvinar leo congue. Sed ante erat, fermentum at auctor ac, molestie in erat. Nunc at mauris nec massa accumsan bibendum. Nunc mollis ipsum a massa lobortis, sed semper risus interdum. Praesent tristique congue mauris a mollis. Ut id felis sodales nibh mollis fringilla quis sed urna. Mauris nec elementum nisl, non imperdiet mi. Donec congue tincidunt turpis, sit amet laoreet tellus suscipit vitae. Cras gravida augue ante, sed dignissim ligula faucibus vitae. Curabitur ut condimentum mi. Cras dignissim, tortor nec iaculis feugiat, lectus massa euismod enim, sed tempus mi arcu in est. Nullam semper dui eros, vel luctus nisl rutrum in.","college@gmail.com"));
            add(new Email("Lorem ipsum dolor sit amet","Pellentesque eu nunc nec magna viverra mollis. Nulla pulvinar magna sed est mattis, consequat pulvinar leo congue. Sed ante erat, fermentum at auctor ac, molestie in erat. Nunc at mauris nec massa accumsan bibendum. Nunc mollis ipsum a massa lobortis, sed semper risus interdum. Praesent tristique congue mauris a mollis. Ut id felis sodales nibh mollis fringilla quis sed urna. Mauris nec elementum nisl, non imperdiet mi. Donec congue tincidunt turpis, sit amet laoreet tellus suscipit vitae. Cras gravida augue ante, sed dignissim ligula faucibus vitae. Curabitur ut condimentum mi. Cras dignissim, tortor nec iaculis feugiat, lectus massa euismod enim, sed tempus mi arcu in est. Nullam semper dui eros, vel luctus nisl rutrum in.","castellblank@gmail.com"));
            add(new Email("Lorem ipsum dolor sit amet","Pellentesque eu nunc nec magna viverra mollis. Nulla pulvinar magna sed est mattis, consequat pulvinar leo congue. Sed ante erat, fermentum at auctor ac, molestie in erat. Nunc at mauris nec massa accumsan bibendum. Nunc mollis ipsum a massa lobortis, sed semper risus interdum. Praesent tristique congue mauris a mollis. Ut id felis sodales nibh mollis fringilla quis sed urna. Mauris nec elementum nisl, non imperdiet mi. Donec congue tincidunt turpis, sit amet laoreet tellus suscipit vitae. Cras gravida augue ante, sed dignissim ligula faucibus vitae. Curabitur ut condimentum mi. Cras dignissim, tortor nec iaculis feugiat, lectus massa euismod enim, sed tempus mi arcu in est. Nullam semper dui eros, vel luctus nisl rutrum in.","rummyes@gmail.com"));
            add(new Email("Lorem ipsum dolor sit amet","Pellentesque eu nunc nec magna viverra mollis. Nulla pulvinar magna sed est mattis, consequat pulvinar leo congue. Sed ante erat, fermentum at auctor ac, molestie in erat. Nunc at mauris nec massa accumsan bibendum. Nunc mollis ipsum a massa lobortis, sed semper risus interdum. Praesent tristique congue mauris a mollis. Ut id felis sodales nibh mollis fringilla quis sed urna. Mauris nec elementum nisl, non imperdiet mi. Donec congue tincidunt turpis, sit amet laoreet tellus suscipit vitae. Cras gravida augue ante, sed dignissim ligula faucibus vitae. Curabitur ut condimentum mi. Cras dignissim, tortor nec iaculis feugiat, lectus massa euismod enim, sed tempus mi arcu in est. Nullam semper dui eros, vel luctus nisl rutrum in.","dummye@gmail.com"));
            add(new Email("Lorem ipsum dolor sit amet","Pellentesque eu nunc nec magna viverra mollis. Nulla pulvinar magna sed est mattis, consequat pulvinar leo congue. Sed ante erat, fermentum at auctor ac, molestie in erat. Nunc at mauris nec massa accumsan bibendum. Nunc mollis ipsum a massa lobortis, sed semper risus interdum. Praesent tristique congue mauris a mollis. Ut id felis sodales nibh mollis fringilla quis sed urna. Mauris nec elementum nisl, non imperdiet mi. Donec congue tincidunt turpis, sit amet laoreet tellus suscipit vitae. Cras gravida augue ante, sed dignissim ligula faucibus vitae. Curabitur ut condimentum mi. Cras dignissim, tortor nec iaculis feugiat, lectus massa euismod enim, sed tempus mi arcu in est. Nullam semper dui eros, vel luctus nisl rutrum in.","dummye@gmail.com"));
            add(new Email("Lorem ipsum dolor sit amet","Pellentesque eu nunc nec magna viverra mollis. Nulla pulvinar magna sed est mattis, consequat pulvinar leo congue. Sed ante erat, fermentum at auctor ac, molestie in erat. Nunc at mauris nec massa accumsan bibendum. Nunc mollis ipsum a massa lobortis, sed semper risus interdum. Praesent tristique congue mauris a mollis. Ut id felis sodales nibh mollis fringilla quis sed urna. Mauris nec elementum nisl, non imperdiet mi. Donec congue tincidunt turpis, sit amet laoreet tellus suscipit vitae. Cras gravida augue ante, sed dignissim ligula faucibus vitae. Curabitur ut condimentum mi. Cras dignissim, tortor nec iaculis feugiat, lectus massa euismod enim, sed tempus mi arcu in est. Nullam semper dui eros, vel luctus nisl rutrum in.","dummye@gmail.com"));
            add(new Email("Lorem ipsum dolor sit amet","Pellentesque eu nunc nec magna viverra mollis. Nulla pulvinar magna sed est mattis, consequat pulvinar leo congue. Sed ante erat, fermentum at auctor ac, molestie in erat. Nunc at mauris nec massa accumsan bibendum. Nunc mollis ipsum a massa lobortis, sed semper risus interdum. Praesent tristique congue mauris a mollis. Ut id felis sodales nibh mollis fringilla quis sed urna. Mauris nec elementum nisl, non imperdiet mi. Donec congue tincidunt turpis, sit amet laoreet tellus suscipit vitae. Cras gravida augue ante, sed dignissim ligula faucibus vitae. Curabitur ut condimentum mi. Cras dignissim, tortor nec iaculis feugiat, lectus massa euismod enim, sed tempus mi arcu in est. Nullam semper dui eros, vel luctus nisl rutrum in.","dummye@gmail.com"));
            add(new Email("Lorem ipsum dolor sit amet","Pellentesque eu nunc nec magna viverra mollis. Nulla pulvinar magna sed est mattis, consequat pulvinar leo congue. Sed ante erat, fermentum at auctor ac, molestie in erat. Nunc at mauris nec massa accumsan bibendum. Nunc mollis ipsum a massa lobortis, sed semper risus interdum. Praesent tristique congue mauris a mollis. Ut id felis sodales nibh mollis fringilla quis sed urna. Mauris nec elementum nisl, non imperdiet mi. Donec congue tincidunt turpis, sit amet laoreet tellus suscipit vitae. Cras gravida augue ante, sed dignissim ligula faucibus vitae. Curabitur ut condimentum mi. Cras dignissim, tortor nec iaculis feugiat, lectus massa euismod enim, sed tempus mi arcu in est. Nullam semper dui eros, vel luctus nisl rutrum in.","dummye@gmail.com"));
            add(new Email("Lorem ipsum dolor sit amet","Pellentesque eu nunc nec magna viverra mollis. Nulla pulvinar magna sed est mattis, consequat pulvinar leo congue. Sed ante erat, fermentum at auctor ac, molestie in erat. Nunc at mauris nec massa accumsan bibendum. Nunc mollis ipsum a massa lobortis, sed semper risus interdum. Praesent tristique congue mauris a mollis. Ut id felis sodales nibh mollis fringilla quis sed urna. Mauris nec elementum nisl, non imperdiet mi. Donec congue tincidunt turpis, sit amet laoreet tellus suscipit vitae. Cras gravida augue ante, sed dignissim ligula faucibus vitae. Curabitur ut condimentum mi. Cras dignissim, tortor nec iaculis feugiat, lectus massa euismod enim, sed tempus mi arcu in est. Nullam semper dui eros, vel luctus nisl rutrum in.","dummye@gmail.com"));
            add(new Email("Lorem ipsum dolor sit amet","Pellentesque eu nunc nec magna viverra mollis. Nulla pulvinar magna sed est mattis, consequat pulvinar leo congue. Sed ante erat, fermentum at auctor ac, molestie in erat. Nunc at mauris nec massa accumsan bibendum. Nunc mollis ipsum a massa lobortis, sed semper risus interdum. Praesent tristique congue mauris a mollis. Ut id felis sodales nibh mollis fringilla quis sed urna. Mauris nec elementum nisl, non imperdiet mi. Donec congue tincidunt turpis, sit amet laoreet tellus suscipit vitae. Cras gravida augue ante, sed dignissim ligula faucibus vitae. Curabitur ut condimentum mi. Cras dignissim, tortor nec iaculis feugiat, lectus massa euismod enim, sed tempus mi arcu in est. Nullam semper dui eros, vel luctus nisl rutrum in.","dummye@gmail.com"));
            add(new Email("Lorem ipsum dolor sit amet","Pellentesque eu nunc nec magna viverra mollis. Nulla pulvinar magna sed est mattis, consequat pulvinar leo congue. Sed ante erat, fermentum at auctor ac, molestie in erat. Nunc at mauris nec massa accumsan bibendum. Nunc mollis ipsum a massa lobortis, sed semper risus interdum. Praesent tristique congue mauris a mollis. Ut id felis sodales nibh mollis fringilla quis sed urna. Mauris nec elementum nisl, non imperdiet mi. Donec congue tincidunt turpis, sit amet laoreet tellus suscipit vitae. Cras gravida augue ante, sed dignissim ligula faucibus vitae. Curabitur ut condimentum mi. Cras dignissim, tortor nec iaculis feugiat, lectus massa euismod enim, sed tempus mi arcu in est. Nullam semper dui eros, vel luctus nisl rutrum in.","dummye@gmail.com"));
            add(new Email("Lorem ipsum dolor sit amet","Pellentesque eu nunc nec magna viverra mollis. Nulla pulvinar magna sed est mattis, consequat pulvinar leo congue. Sed ante erat, fermentum at auctor ac, molestie in erat. Nunc at mauris nec massa accumsan bibendum. Nunc mollis ipsum a massa lobortis, sed semper risus interdum. Praesent tristique congue mauris a mollis. Ut id felis sodales nibh mollis fringilla quis sed urna. Mauris nec elementum nisl, non imperdiet mi. Donec congue tincidunt turpis, sit amet laoreet tellus suscipit vitae. Cras gravida augue ante, sed dignissim ligula faucibus vitae. Curabitur ut condimentum mi. Cras dignissim, tortor nec iaculis feugiat, lectus massa euismod enim, sed tempus mi arcu in est. Nullam semper dui eros, vel luctus nisl rutrum in.","dummye@gmail.com"));
            add(new Email("Lorem ipsum dolor sit amet","Pellentesque eu nunc nec magna viverra mollis. Nulla pulvinar magna sed est mattis, consequat pulvinar leo congue. Sed ante erat, fermentum at auctor ac, molestie in erat. Nunc at mauris nec massa accumsan bibendum. Nunc mollis ipsum a massa lobortis, sed semper risus interdum. Praesent tristique congue mauris a mollis. Ut id felis sodales nibh mollis fringilla quis sed urna. Mauris nec elementum nisl, non imperdiet mi. Donec congue tincidunt turpis, sit amet laoreet tellus suscipit vitae. Cras gravida augue ante, sed dignissim ligula faucibus vitae. Curabitur ut condimentum mi. Cras dignissim, tortor nec iaculis feugiat, lectus massa euismod enim, sed tempus mi arcu in est. Nullam semper dui eros, vel luctus nisl rutrum in.","dummye@gmail.com"));
            add(new Email("Lorem ipsum dolor sit amet","Pellentesque eu nunc nec magna viverra mollis. Nulla pulvinar magna sed est mattis, consequat pulvinar leo congue. Sed ante erat, fermentum at auctor ac, molestie in erat. Nunc at mauris nec massa accumsan bibendum. Nunc mollis ipsum a massa lobortis, sed semper risus interdum. Praesent tristique congue mauris a mollis. Ut id felis sodales nibh mollis fringilla quis sed urna. Mauris nec elementum nisl, non imperdiet mi. Donec congue tincidunt turpis, sit amet laoreet tellus suscipit vitae. Cras gravida augue ante, sed dignissim ligula faucibus vitae. Curabitur ut condimentum mi. Cras dignissim, tortor nec iaculis feugiat, lectus massa euismod enim, sed tempus mi arcu in est. Nullam semper dui eros, vel luctus nisl rutrum in.","dummye@gmail.com"));
            add(new Email("Lorem ipsum dolor sit amet","Pellentesque eu nunc nec magna viverra mollis. Nulla pulvinar magna sed est mattis, consequat pulvinar leo congue. Sed ante erat, fermentum at auctor ac, molestie in erat. Nunc at mauris nec massa accumsan bibendum. Nunc mollis ipsum a massa lobortis, sed semper risus interdum. Praesent tristique congue mauris a mollis. Ut id felis sodales nibh mollis fringilla quis sed urna. Mauris nec elementum nisl, non imperdiet mi. Donec congue tincidunt turpis, sit amet laoreet tellus suscipit vitae. Cras gravida augue ante, sed dignissim ligula faucibus vitae. Curabitur ut condimentum mi. Cras dignissim, tortor nec iaculis feugiat, lectus massa euismod enim, sed tempus mi arcu in est. Nullam semper dui eros, vel luctus nisl rutrum in.","dummye@gmail.com"));
            add(new Email("Lorem ipsum dolor sit amet","Pellentesque eu nunc nec magna viverra mollis. Nulla pulvinar magna sed est mattis, consequat pulvinar leo congue. Sed ante erat, fermentum at auctor ac, molestie in erat. Nunc at mauris nec massa accumsan bibendum. Nunc mollis ipsum a massa lobortis, sed semper risus interdum. Praesent tristique congue mauris a mollis. Ut id felis sodales nibh mollis fringilla quis sed urna. Mauris nec elementum nisl, non imperdiet mi. Donec congue tincidunt turpis, sit amet laoreet tellus suscipit vitae. Cras gravida augue ante, sed dignissim ligula faucibus vitae. Curabitur ut condimentum mi. Cras dignissim, tortor nec iaculis feugiat, lectus massa euismod enim, sed tempus mi arcu in est. Nullam semper dui eros, vel luctus nisl rutrum in.","dummye@gmail.com"));
            add(new Email("Lorem ipsum dolor sit amet","Pellentesque eu nunc nec magna viverra mollis. Nulla pulvinar magna sed est mattis, consequat pulvinar leo congue. Sed ante erat, fermentum at auctor ac, molestie in erat. Nunc at mauris nec massa accumsan bibendum. Nunc mollis ipsum a massa lobortis, sed semper risus interdum. Praesent tristique congue mauris a mollis. Ut id felis sodales nibh mollis fringilla quis sed urna. Mauris nec elementum nisl, non imperdiet mi. Donec congue tincidunt turpis, sit amet laoreet tellus suscipit vitae. Cras gravida augue ante, sed dignissim ligula faucibus vitae. Curabitur ut condimentum mi. Cras dignissim, tortor nec iaculis feugiat, lectus massa euismod enim, sed tempus mi arcu in est. Nullam semper dui eros, vel luctus nisl rutrum in.","dummye@gmail.com"));
            add(new Email("Lorem ipsum dolor sit amet","Pellentesque eu nunc nec magna viverra mollis. Nulla pulvinar magna sed est mattis, consequat pulvinar leo congue. Sed ante erat, fermentum at auctor ac, molestie in erat. Nunc at mauris nec massa accumsan bibendum. Nunc mollis ipsum a massa lobortis, sed semper risus interdum. Praesent tristique congue mauris a mollis. Ut id felis sodales nibh mollis fringilla quis sed urna. Mauris nec elementum nisl, non imperdiet mi. Donec congue tincidunt turpis, sit amet laoreet tellus suscipit vitae. Cras gravida augue ante, sed dignissim ligula faucibus vitae. Curabitur ut condimentum mi. Cras dignissim, tortor nec iaculis feugiat, lectus massa euismod enim, sed tempus mi arcu in est. Nullam semper dui eros, vel luctus nisl rutrum in.","dummye@gmail.com"));
            add(new Email("Lorem ipsum dolor sit amet","Pellentesque eu nunc nec magna viverra mollis. Nulla pulvinar magna sed est mattis, consequat pulvinar leo congue. Sed ante erat, fermentum at auctor ac, molestie in erat. Nunc at mauris nec massa accumsan bibendum. Nunc mollis ipsum a massa lobortis, sed semper risus interdum. Praesent tristique congue mauris a mollis. Ut id felis sodales nibh mollis fringilla quis sed urna. Mauris nec elementum nisl, non imperdiet mi. Donec congue tincidunt turpis, sit amet laoreet tellus suscipit vitae. Cras gravida augue ante, sed dignissim ligula faucibus vitae. Curabitur ut condimentum mi. Cras dignissim, tortor nec iaculis feugiat, lectus massa euismod enim, sed tempus mi arcu in est. Nullam semper dui eros, vel luctus nisl rutrum in.","dummye@gmail.com"));
        }};
    }
}
